### ISSUE TITLE
Create a generic framework for name references

### ISSUE THREAD

**Issue by arikkfir** [arikkfir/kude#15]
Allow a resource to specify an "externalName" (in addition to its standard Kubernetes name), probably through an annotation; that external name will be used by Kude to find references to that external name elsewhere, and replace those references with the actual Kubernetes name of that resource.

For example:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cfg-aj491djs2
  namespace: main
  annotation:
    # this annotation tells Kude to replace references ConfigMaps named
    # "cfg" in namespace "main" to the actual name of this resource
    kude.kfirs.com/externalName: cfg
data:
  foo: bar
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: server
    env:
    - name: FOO
      valueFrom:
        configMapKeyRef:
          name: cfg # this should be replaced with "cfg-aj491djs2"
          key: foo
```
