### ISSUE TITLE
Extend `label-selector` of functions for more use-cases

### ISSUE THREAD

**Issue by arikkfir** [arikkfir/kude#84]
Support targeting specific resource types as well.

Something like this:

```yaml
- image: .../annotate
  config:
    name: my-annotation

    # annotate any resource matching ANY of the following predicates (logical OR)
    targets:
      # This will annotate all resources of type "Namespace" (even if they are not of API version "v1")
      - kind: Namespace

      # This will annotate all service accounts (this is more specific, using the "apiVersion"...)
      - apiVersion: v1 
        kind: ServiceAccount

      # This will annotate all config maps with the label "component=mysql"
      - apiVersion: v1
        kind: ConfigMap
        labels:
          component: mysql
```
